name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup Node and npm auth
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      # Enable Yarn and install deps
      - run: |
          corepack enable
          corepack prepare yarn@4.3.1 --activate
          yarn config set nodeLinker node-modules
          yarn install --immutable

      # Build all packages (assuming you use a root build script)
      - run: yarn build

      - name: Publish agent-sdk-typescript
        working-directory: packages/agent-sdk-typescript
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish api-types
        working-directory: packages/api-types
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
