# .github/workflows/release.yml
name: Release

on:
  push:
    branches: [main]          # publish happens when the version-bump PR is merged
  workflow_dispatch:          # allow manual runs if ever needed

permissions:
  contents: write             # allow creating tags / release commit
  packages: write             # (optional) for GH Packages; harmless for npm-only
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣  Grab the repo (incl. tags so Changesets can diff)
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️⃣  Install the requested Node and enable Corepack (Yarn ≥2)
      - name: Setup Node & Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Activate Yarn 4.3.1 with node_modules linker
        run: |
          corepack enable
          corepack prepare yarn@4.3.1 --activate
          yarn config set nodeLinker node-modules
          yarn -v    # sanity check → 4.3.1

      # 3️⃣  Install deps deterministically
      - name: Install dependencies
        run: yarn install --immutable          # fails if lockfile out of sync

      # 4️⃣  Build everything (uses your root "build" script)
      - name: Build
        run: yarn build

      # 5️⃣  Let Changesets do its thing
      #     – If there are still un-versioned changesets → opens/updates a PR
      #     – If the commit already contains version bumps → publishes to npm
      - name: Create release PR or publish
        uses: changesets/action@v1
        with:
          publish: yarn changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # auto-provided
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}   # add this secret in repo → Settings → Secrets → Actions
